import { productT } from "@/types";

 export  const products: productT[] = [
    {
      id: "prod001",
      name: "Elegant Jamdani Saree",
      description: "A handcrafted Jamdani saree with intricate floral patterns, perfect for festive occasions.",
      price: 120.0,
      discount: 10,
      category: "Women",
      subCategory: "Sarees",
      sizes: ["Free Size"],
      colors: ["White", "Golden"],
      materials: ["Cotton", "Silk"],
      images: [
        "/kurta-pajamas.png",
        "/salwar-kameez.jpg",
      ],
      isFeatured: true,
      isNewArrival: false,
      isBestSeller: true,
      stock: 15,
      ratings: {
        average: 4.8,
        count: 120,
      },
      reviews: [
        {
          userId: "user101",
          comment: "Absolutely stunning! The quality is exceptional.",
          rating: 5,
          date: "2024-01-01",
        },
        {
          userId: "user202",
          comment: "Beautiful saree, but the shipping was delayed.",
          rating: 4,
          date: "2024-01-02",
        },
      ],
      tags: ["Festive", "Handmade"],
      careInstructions: "Dry clean only.",
      shippingInfo: "Ships within 3 days.",
      brand: "Bangla Heritage",
      sku: "JMDN-001",
      returnPolicy: "Eligible for return within 7 days.",
      createdAt: "2023-12-25",
      updatedAt: "2023-12-30",
    },
    {
      id: "prod002",
      name: "Men's Classic Panjabi",
      description: "A classic white cotton panjabi, lightweight and perfect for both casual and formal occasions.",
      price: 35.0,
      category: "Men",
      subCategory: "Panjabis",
      sizes: ["M", "L", "XL"],
      colors: ["White"],
      materials: ["Cotton"],
      images: [
        "/salwar-kameez.jpg",
        "/shop-slider-img2.png",
        "/shop-slider-img3.png"
      ],
      isFeatured: false,
      isNewArrival: true,
      isBestSeller: false,
      stock: 50,
      ratings: {
        average: 4.2,
        count: 75,
      },
      reviews: [
        {
          userId: "user303",
          comment: "Comfortable and well-fitted. Great for summer!",
          rating: 4,
          date: "2024-01-03",
        },
      ],
      tags: ["Casual", "Traditional"],
      careInstructions: "Machine wash cold, tumble dry low.",
      shippingInfo: "Ships within 2 days.",
      brand: "Deshi Threads",
      sku: "PNJB-002",
      returnPolicy: "Exchange only within 7 days.",
      createdAt: "2023-12-20",
    },
    {
      id: "prod003",
      name: "Kid's Festive Lehenga",
      description: "A colorful and comfortable lehenga set for kids, designed for joyous celebrations.",
      price: 50.0,
      discount: 5,
      category: "Kids",
      subCategory: "Festive Wear",
      sizes: ["S", "M", "L"],
      colors: ["Pink", "Blue"],
      materials: ["Silk", "Net"],
      images: [
        "/dapper sherwanis.jpg",
        "/lehengas.jpg",
      ],
      isFeatured: true,
      isNewArrival: true,
      isBestSeller: true,
      stock: 30,
      ratings: {
        average: 4.7,
        count: 45,
      },
      reviews: [
        {
          userId: "user404",
          comment: "My daughter loved it! Perfect for weddings.",
          rating: 5,
          date: "2024-01-04",
        },
      ],
      tags: ["Festive", "Colorful"],
      careInstructions: "Hand wash only.",
      shippingInfo: "Ships within 5 days.",
      brand: "Tiny Traditions",
      sku: "KLHG-003",
      returnPolicy: "Eligible for return within 5 days.",
      createdAt: "2023-12-18",
    },
    {
      id: "prod001",
      name: "Elegant Jamdani Saree",
      description: "A handcrafted Jamdani saree with intricate floral patterns, perfect for festive occasions.",
      price: 120.0,
      discount: 10,
      category: "Women",
      subCategory: "Sarees",
      sizes: ["Free Size"],
      colors: ["White", "Golden"],
      materials: ["Cotton", "Silk"],
      images: [
        "/kurta-pajamas.png",
        "/salwar-kameez.jpg",
      ],
      isFeatured: true,
      isNewArrival: false,
      isBestSeller: true,
      stock: 15,
      ratings: {
        average: 4.8,
        count: 120,
      },
      reviews: [
        {
          userId: "user101",
          comment: "Absolutely stunning! The quality is exceptional.",
          rating: 5,
          date: "2024-01-01",
        },
        {
          userId: "user202",
          comment: "Beautiful saree, but the shipping was delayed.",
          rating: 4,
          date: "2024-01-02",
        },
      ],
      tags: ["Festive", "Handmade"],
      careInstructions: "Dry clean only.",
      shippingInfo: "Ships within 3 days.",
      brand: "Bangla Heritage",
      sku: "JMDN-001",
      returnPolicy: "Eligible for return within 7 days.",
      createdAt: "2023-12-25",
      updatedAt: "2023-12-30",
    },
  ];